#服务端口
server:
    port: 8110


#文件上传
  #存储类型
ufop:
    storage-type: 0
  #文件存储路径
    local-storage-path:
  #图片缩略图
    thumb-image.width: 150
    thumb-image.height: 150

# 环境设置
spring:
    profiles.active: dev
    # 服务名
    application:
        name: service-core
    datasource: # mysql数据库连接
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/file?serverTimezone=GMT%2B8&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        url: jdbc:mysql://localhost:3306/file?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=true
        username: root
        password: 123456

    #上传下载
    servlet:
        multipart:
            max-file-size: 2048MB
            max-request-size: 2048MB
            enabled: true
    #后发现的bean会覆盖之前相同名称的bean
    main:
        allow-bean-definition-overriding: true

    # nacos服务地址
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848 # nacos服务地址

    redis:
        host: 192.168.138.107
        port: 6379
        database: 0
        #password: 123456 #默认为空
        timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
        lettuce:
            pool:
                max-active: 20  #最大连接数，负值表示没有限制，默认8
                max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
                max-idle: 8     #最大空闲连接，默认8
                min-idle: 0     #最小空闲连接，默认0


#mybatis
mybatis-plus: #mybatis
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/zsxfa/cloud/core/mapper/xml/*.xml

# 当前部署外网IP，用于office文件编辑和预览
deployment.host: 192.168.0.117